import { Product, Category, Order } from '@/types';

export const MOCK_CATEGORIES: Category[] = [
  {
    _id: 'cat-1',
    name: 'Women Ethnic',
    slug: 'women-ethnic',
    depth: 0,
    displayOrder: 1,
    isActive: true,
    image: {
      url: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=300&q=80',
    },
  },
  {
    _id: 'cat-2',
    name: 'Women Western',
    slug: 'women-western',
    depth: 0,
    displayOrder: 2,
    isActive: true,
    image: {
      url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=300&q=80',
    },
  },
  {
    _id: 'cat-3',
    name: 'Men Fashion',
    slug: 'men-fashion',
    depth: 0,
    displayOrder: 3,
    isActive: true,
    image: {
      url: 'https://images.unsplash.com/photo-1617137984095-74e4e5e3613f?auto=format&fit=crop&w=300&q=80',
    },
  },
  {
    _id: 'cat-4',
    name: 'Kids & Baby',
    slug: 'kids-baby',
    depth: 0,
    displayOrder: 4,
    isActive: true,
    image: {
      url: 'https://images.unsplash.com/photo-1514090458221-65bb69cf63e6?auto=format&fit=crop&w=300&q=80',
    },
  },
  {
    _id: 'cat-5',
    name: 'Home & Kitchen',
    slug: 'home-kitchen',
    depth: 0,
    displayOrder: 5,
    isActive: true,
    image: {
      url: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=300&q=80',
    },
  },
  {
    _id: 'cat-6',
    name: 'Beauty & Health',
    slug: 'beauty-health',
    depth: 0,
    displayOrder: 6,
    isActive: true,
    image: {
      url: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=300&q=80',
    },
  },
  {
    _id: 'cat-7',
    name: 'Footwear',
    slug: 'footwear',
    depth: 0,
    displayOrder: 7,
    isActive: true,
    image: {
      url: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=300&q=80',
    },
  },
  {
    _id: 'cat-8',
    name: 'Electronics',
    slug: 'electronics',
    depth: 0,
    displayOrder: 8,
    isActive: true,
    image: {
      url: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=300&q=80',
    },
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    _id: 'prod-1',
    title: 'Embroidered Anarkali Kurta Set with Dupatta',
    slug: 'embroidered-anarkali-kurta-set-dupatta',
    description: 'Graceful rayon cotton embroidered Anarkali kurti with matching pant and chiffon dupatta.',
    brand: 'Libas Trendz',
    category: 'cat-1',
    seller: {
      _id: 'sel-1',
      storeName: 'Vandana Creations Surat',
      ratingAvg: 4.6,
    },
    images: [
      {
        url: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=600&q=80',
        isPrimary: true,
      },
    ],
    basePrice: 1999,
    discountPercent: 65,
    finalPrice: 699,
    tags: ['trending', 'ethnic', 'sale', 'women'],
    ratingAvg: 4.4,
    ratingCount: 3412,
    totalSold: 12500,
    status: 'active',
    isCOD: true,
    returnWindowDays: 7,
  },
  {
    _id: 'prod-2',
    title: 'Solid Regular Fit Cotton Casual Shirt',
    slug: 'solid-regular-fit-cotton-casual-shirt',
    description: '100% breathable pure combed cotton regular fit button-down shirt for men.',
    brand: 'Dennis Lingo',
    category: 'cat-3',
    seller: {
      _id: 'sel-2',
      storeName: 'Bengaluru Garments Hub',
      ratingAvg: 4.3,
    },
    images: [
      {
        url: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=600&q=80',
        isPrimary: true,
      },
    ],
    basePrice: 1499,
    discountPercent: 67,
    finalPrice: 489,
    tags: ['budget', 'men', 'shirts'],
    ratingAvg: 4.2,
    ratingCount: 1890,
    totalSold: 8400,
    status: 'active',
    isCOD: true,
    returnWindowDays: 7,
  },
  {
    _id: 'prod-3',
    title: 'Kanjeevaram Jacquard Woven Art Silk Saree',
    slug: 'kanjeevaram-jacquard-woven-art-silk-saree',
    description: 'Traditional heavy zari border art silk saree with unstitched blouse piece.',
    brand: 'Kashvi Sarees',
    category: 'cat-1',
    seller: {
      _id: 'sel-3',
      storeName: 'Varanasi Weavers Co',
      ratingAvg: 4.8,
    },
    images: [
      {
        url: 'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=600&q=80',
        isPrimary: true,
      },
    ],
    basePrice: 2999,
    discountPercent: 73,
    finalPrice: 799,
    tags: ['top_rated', 'sarees', 'festive'],
    ratingAvg: 4.7,
    ratingCount: 5620,
    totalSold: 21000,
    status: 'active',
    isCOD: true,
    returnWindowDays: 7,
  },
  {
    _id: 'prod-4',
    title: 'Lightweight Breathable Mesh Running Shoes',
    slug: 'lightweight-breathable-mesh-running-shoes',
    description: 'High-grip EVA sole athletic trainers engineered for maximum walking cushion.',
    brand: 'Asian Footwear',
    category: 'cat-7',
    seller: {
      _id: 'sel-4',
      storeName: 'Delhi Sports World',
      ratingAvg: 4.1,
    },
    images: [
      {
        url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=600&q=80',
        isPrimary: true,
      },
    ],
    basePrice: 1299,
    discountPercent: 62,
    finalPrice: 499,
    tags: ['shoes', 'under_499', 'men'],
    ratingAvg: 4.3,
    ratingCount: 2847,
    totalSold: 9700,
    status: 'active',
    isCOD: true,
    returnWindowDays: 7,
  },
  {
    _id: 'prod-5',
    title: 'Floral Print Georgette Fit & Flare Maxi Dress',
    slug: 'floral-print-georgette-fit-flare-maxi-dress',
    description: 'Chic boho print tier layered western dress with comfortable inner lining.',
    brand: 'Berrylush',
    category: 'cat-2',
    seller: {
      _id: 'sel-5',
      storeName: 'Jaipur Fashion House',
      ratingAvg: 4.5,
    },
    images: [
      {
        url: 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?auto=format&fit=crop&w=600&q=80',
        isPrimary: true,
      },
    ],
    basePrice: 1899,
    discountPercent: 58,
    finalPrice: 799,
    tags: ['western', 'women', 'trending'],
    ratingAvg: 4.5,
    ratingCount: 1420,
    totalSold: 6300,
    status: 'active',
    isCOD: true,
    returnWindowDays: 7,
  },
  {
    _id: 'prod-6',
    title: 'Wireless Bluetooth Earbuds with 40H Playtime',
    slug: 'wireless-bluetooth-earbuds-40h-playtime',
    description: 'ENC noise cancellation, IPX5 water resistance, deep bass 13mm drivers.',
    brand: 'boAt Lifestyle',
    category: 'cat-8',
    seller: {
      _id: 'sel-6',
      storeName: 'TechGizmo Direct',
      ratingAvg: 4.4,
    },
    images: [
      {
        url: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=600&q=80',
        isPrimary: true,
      },
    ],
    basePrice: 2490,
    discountPercent: 64,
    finalPrice: 899,
    tags: ['electronics', 'audio', 'top_rated'],
    ratingAvg: 4.4,
    ratingCount: 8930,
    totalSold: 32000,
    status: 'active',
    isCOD: true,
    returnWindowDays: 7,
  },
];

export const MOCK_ORDERS: Order[] = [
  {
    _id: 'ord-101',
    orderNumber: 'ORD-260920-83921',
    user: 'usr-1',
    items: [
      {
        product: MOCK_PRODUCTS[0],
        seller: 'sel-1',
        titleSnapshot: MOCK_PRODUCTS[0].title,
        imageSnapshot: MOCK_PRODUCTS[0].images[0].url,
        priceSnapshot: 699,
        sizeSnapshot: 'M',
        colourSnapshot: 'Maroon',
        qty: 1,
        itemStatus: 'delivered',
      },
    ],
    shippingAddress: {
      _id: 'addr-1',
      fullName: 'Parth Shandilya',
      phone: '9876543210',
      line1: 'Flat 402, Sunshine Heights, 100ft Road',
      city: 'Bengaluru',
      state: 'Karnataka',
      pincode: '560038',
      type: 'home',
      isDefault: true,
    },
    pricing: {
      subtotal: 699,
      discount: 0,
      couponDiscount: 50,
      couponCode: 'WELCOME50',
      shippingFee: 0,
      tax: 32,
      grandTotal: 681,
    },
    paymentMethod: 'online',
    paymentStatus: 'paid',
    orderStatus: 'delivered',
    statusHistory: [
      { status: 'placed', note: 'Order placed via UPI', at: '2026-09-15T10:00:00Z' },
      { status: 'confirmed', note: 'Confirmed by seller', at: '2026-09-15T11:30:00Z' },
      { status: 'packed', note: 'Packed at Surat Hub', at: '2026-09-16T09:00:00Z' },
      { status: 'shipped', note: 'Dispatched via BlueDart AW# 839201', at: '2026-09-17T14:00:00Z' },
      { status: 'out_for_delivery', note: 'Courier out for delivery', at: '2026-09-19T08:30:00Z' },
      { status: 'delivered', note: 'Delivered to customer', at: '2026-09-19T16:45:00Z' },
    ],
    createdAt: '2026-09-15T10:00:00Z',
  },
];
